### ISSUE TITLE
React-Bootstrap 1.1.1 throwing TypeScript error Declaration of statement expected

### ISSUE THREAD

**Issue by overtureweb** [react-bootstrap/react-bootstrap#5281]
## Describe the bug

Project fails to compile: TypeScript error in /Users/alexwarner/PhpstormProjects/test-project/node_modules/react-bootstrap/esm/index.d.ts(5,1):
Declaration or statement expected.  TS1128

## To Reproduce

1. Use CRA to setup new React project
2. Install react-bootstrap npm install react-bootstrap bootstrap
3. Import any bootstrap component: import {Form} from "react-bootstrap"
4. When the app compiles the above error is thrown

## Screenshots
<img width="719" alt="Screen Shot 2020-07-08 at 1 13 13 PM" src="https://user-images.githubusercontent.com/20868338/86965850-0298c480-c11d-11ea-8130-aae92563c1c8.png">
<img width="981" alt="Screen Shot 2020-07-08 at 1 13 04 PM" src="https://user-images.githubusercontent.com/20868338/86965899-117f7700-c11d-11ea-99a2-8e667cb0a1f4.png">

## Environment (please complete the following information)

- Operating System: [e.g. macOS 10.15.5]
- Browser, Version [Firefox 77]
- React-Bootstrap Version [1.1.1]

## Additional context

See screenshot above, in the index.d.ts file included in the RB package my code linter is flagging errors on any line using the syntax,`export type { AccordionProps } from './Accordion';`

**Comment by jquense** [comment]
what version of typescript are you using?

**Comment by overtureweb** [comment]
Sorry "typescript": "^3.7.5" is in the package.json

**Comment by jquense** [comment]
type imports were added in typescript 3.8, upgrade and it should be fixed

**Comment by overtureweb** [comment]
Thanks so much for your help. Forgive me if this was already included in the documentation but if not, perhaps it would be helpful to add this. 1.0.1 -> 1.1.1 is a minor release but now has breaking changes. But then again maybe most developers are already using TS 3.8+

**Comment by jquense** [comment]
The breaking changes are only in the type definitions, which isn't something we can guarentee won't break between any version just because of how typescript works. This generally how DT type definitions work as well (and typescript itself). Code that worked in 1.0.1 will all still work in 1.1.0 but you may get a new TS error. We try our best to prevent it but sometimes it's not possible, especially when the type was wrong previously

**Comment by gtrj55** [comment]
Hi I also face the same error, i upgrade my version of typescript, currently it is Version 3.9.7. but still code is not working, below is the error
Please help me to sort this issue

Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(2,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(2,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(2,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(5,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(5,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(5,45): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(7,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(7,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(7,43): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(9,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(9,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(9,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(11,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(11,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(11,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(13,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(13,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(13,38): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(15,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(15,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(15,42): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(17,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(17,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(17,34): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(19,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(19,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(19,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(21,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(21,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(21,41): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(23,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(23,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(23,32): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(27,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(27,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(27,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(30,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(30,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(30,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(33,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(33,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(33,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(35,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(35,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(35,31): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(37,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(37,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(37,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(39,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(39,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(39,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(41,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(41,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(41,42): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(43,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(43,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(43,32): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(45,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(45,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(45,32): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(47,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(47,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(47,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(49,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(49,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(49,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(51,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(51,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(51,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(53,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(53,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(53,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(55,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(55,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(55,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(57,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(57,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(57,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(59,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(59,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(59,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(61,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(61,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(61,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(64,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(64,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(64,38): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(66,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(66,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(66,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(68,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(68,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(68,37): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(70,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(70,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(70,41): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(73,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(73,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(73,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(76,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(76,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(76,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(80,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(80,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(80,31): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(82,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(82,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(82,34): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(84,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(84,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(84,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(86,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(86,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(86,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(88,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(88,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(88,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(90,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(90,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(90,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(92,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(92,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(92,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(94,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(94,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(94,42): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(96,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(96,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(96,36): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(98,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(98,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(98,38): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(100,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(100,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(100,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(104,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(104,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(104,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(106,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(106,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(106,43): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(108,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(108,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(108,31): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(110,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(110,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(110,38): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(112,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(112,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(112,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(114,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(114,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(114,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(116,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(116,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(116,31): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(118,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(118,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(118,40): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(121,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(121,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(121,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(123,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(123,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(123,35): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(125,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(125,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(125,32): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(127,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(127,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(127,41): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(129,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(129,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(129,33): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(132,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(132,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(132,39): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(134,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(134,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(134,40): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(136,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(136,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(136,90): error TS1109: Expression expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(136,97): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(138,1): error TS1128: Declaration or statement expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(138,13): error TS1005: ';' expected.
[11:38:05] Error - [tsc] node_modules/react-bootstrap/esm/index.d.ts(138,35): error TS1005: ';' expected.
[11:38:05] Error - 'tsc' sub task errored after 8.23 s 
 exited with code 2

**Comment by gtrj55** [comment]
I also get this error, but solution is different , i imported like this : import {Button} from 'react-bootstrap/Button', so this give me an error so i changed the way of writing =import Button from 'react-bootstrap/Button', this work for me,

**Comment by Salzian** [comment]
Maybe some additional info since I see you use some JetBrains product. When I was using WebStorm's build-in React App template, it defaulted to use an outdated version 3.7.x of typescript. You'll need to manually bump the version then.

**Comment by jefelewis** [comment]
> type imports were added in typescript 3.8, upgrade and it should be fixed

This worked for me. My TypeScript version was 3.7.X and I just upgraded to 3.9.X, which fixed the error.

**Comment by salarease** [comment]
> 
> 
> type imports were added in typescript 3.8, upgrade and it should be fixed

Thanks for this. You save my life ;)

**Comment by SolucionARG** [comment]
I'm still having this problem and I have 3.9.7. I try with a new project, just adding  import Container from 'react-bootstrap'; creates the error.

**Comment by bpolzar** [comment]
> I'm still having this problem and I have 3.9.7. I try with a new project, just adding import Container from 'react-bootstrap'; creates the error.

For those using VS Code, make sure that your workspace / project version are accurate and not just the editor version. I struggled for a minute wondering what was going on until I checked my package.json file and saw that version was only 3.7.X though my editor was using 3.9.X. Upgrading the version fixed the issue.

**Comment by RagibHossain** [comment]
> > I'm still having this problem and I have 3.9.7. I try with a new project, just adding import Container from 'react-bootstrap'; creates the error.
> 
> For those using VS Code, make sure that your workspace / project version are accurate and not just the editor version. I struggled for a minute wondering what was going on until I checked my package.json file and saw that version was only 3.7.X though my editor was using 3.9.X. Upgrading the version fixed the issue.

Do you just change the 3.7.X to 3.9.X in package.json file manually.

**Comment by SolucionARG** [comment]
sorry, I'm kind of new in react. You are right, the package.json file is still 3.7.5 but I don't know how to upgrade it, would you help me? Thanks for your attention.

**Comment by RagibHossain** [comment]
> sorry, I'm kind of new in react. You are right, the package.json file is still 3.7.5 but I don't know how to upgrade it, would you help me? Thanks for your attention.

Bro, have you installed 3.9.7 using (npm install -g typescript@latest) this command?

**Comment by SolucionARG** [comment]
> sorry, I'm kind of new in react. You are right, the package.json file is still 3.7.5 but I don't know how to upgrade it, would you help me? Thanks for your attention.
> 
> Bro, have you installed 3.9.7 using (npm install -g typescript@latest) this command?

yes, after that I created a new project using create-react-app but the json of thay new one still shows 3.7.5

**Comment by RagibHossain** [comment]
> > sorry, I'm kind of new in react. You are right, the package.json file is still 3.7.5 but I don't know how to upgrade it, would you help me? Thanks for your attention.
> > Bro, have you installed 3.9.7 using (npm install -g typescript@latest) this command?
> 
> yes, after that I created a new project using create-react-app but the json of thay new one still shows 3.7.5

bro i am having the same problem. But I solved it in a different a way . Whatever component you are importing from React-Bootstrap import it this way. For e.g if you are importing Button (import Button from "react-bootstrap/Button") instead of        
( import {Button} from "react-bootstrap") . Let me know if this solves the problem

**Comment by SolucionARG** [comment]
Great! It works perfect importing that way. Thanks a lot for your help.

**Comment by HeyJude1** [comment]
@SolucionARG, @RagibHossain, after changing typescript's version in your `package.json` to `3.9.X`, you should also run `npm install` in your project directory, and you're all set.

**Comment by gabe2code** [comment]
The same problem with typescript 4.02

**Comment by ghwlchlaks** [comment]
Great! thanks a lot for you help! 
1. node_modules/typescript remove
2. package.json "typescript": 3.7.3 remove
3. typescript reinstall => npm install typescript

**Comment by dkryshtopenko** [comment]
> type imports were added in typescript 3.8, upgrade and it should be fixed

God bless you
