### ISSUE TITLE
Feature: replace react-transition-group with a modern alternative

### ISSUE THREAD

**Issue by shansean** [react-bootstrap/react-bootstrap#6884]
### Is your feature request related to a problem? Please describe

react-transition-group has not had any new versions in two years.

It relies on some ReactDOM methods that have been removed in react 19.
https://github.com/reactjs/react-transition-group/issues/904

### Describe the solution you'd like

react-transition-group should probably be replaced with a newer library that is being maintained such as [react-transition-state](https://www.npmjs.com/package/react-transition-state)

**Comment by halibal** [comment]
This is a problem I run into after upgrading an application's React version from 18 to 19, as well. 

`React 19` removed the `findDOMNode` method, and this breaks the app whenever it is called. 

`React-Bootstrap` does not directly use this method; instead, it relies on another package using it: `react-transition-group.`

Error occurs as follows in `Transition2` component:

```
Uncaught TypeError:
import_react_dom.default.findDOMNode is not a function

at Transition2.updateStatus
at Transition2.componentDidMount
```

**Comment by kyletsang** [comment]
> This is a problem I run into after upgrading an application's React version from 18 to 19, as well.
> 
> `React 19` removed the `findDOMNode` method, and this breaks the app whenever it is called.
> 
> `React-Bootstrap` does not directly use this method; instead, it relies on another package using it: `react-transition-group.`
> 
> Error occurs as follows in `Transition2` component:
> 
> ```
> Uncaught TypeError:
> import_react_dom.default.findDOMNode is not a function
> 
> at Transition2.updateStatus
> at Transition2.componentDidMount
> ```

Do you have a full call stack/sample code?  We do use RTG's `nodeRef` prop that should've bypassed the usage of most cases of `findDOMNode` in RTG.
