### ISSUE TITLE
After migrating to 1.3.0 I can't use Tab

### ISSUE THREAD

**Issue by felipecarrillo100** [react-bootstrap/react-bootstrap#5354]
## After migrating to 1.3.0 I can't use Tab

My code used to work fine with react-bootstrap 1.0.1. But after migrating to 1.3.0, I get this error when I try to use <Tab />

TS2786: 'Tab' cannot be used as a JSX component.
  Its instance type 'Tab' is not a valid JSX element.
    Type 'Tab' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

And I also get this error:
TS2607: JSX element class does not support attributes because it does not have a 'props' property.

Both are Typescript compilation errors

## This could be related to my Typescript configuration but not sure.  
Here a copy of my tsconfig.json

```
{
  "compilerOptions": {
    "sourceMap": true,
    "jsx": "react",
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "./src/**/*",
    "./test/**/*"
  ]
}
```

## Environment (please complete the following information)

- Operating System: Windows 10
- React-Bootstrap Version 1.3.0

## Additional context

This could be an issue in my Typescript configuration, but it is strange that it used to work just fine in react-bootstrap 1.0.1

**Comment by felipecarrillo100** [comment]
I forked react-bootstrap/esm/Tab.d.ts
Then I replaced 
```
import React from 'react';

```
by

```
import * as React from 'react';

```
This solves the issue I described.  Could you please add this change in the next release? Any developer who uses a similar Typescript configuration as me will experience the same problem. Notice that import * as React from 'react' is a more suitable import with better compatibility.

**Comment by jquense** [comment]
i don't understand TS' logic here, `import * as React` is _not_ more correct given that the types only define a CommonJS export `exports = ...`, If we were to assume a real ESM environment importing a common JS module, `import React from` is the only one that would actually work. 

in any case i would enable `esModuleInterop` or `allowSyntheticDefaultImports` in your tsconfig, to fix this.

**Comment by felipecarrillo100** [comment]
Is not a question of is more correct,  but compatibility issue.  You are forcing the users of your library to your a specific TS configuration.  Before in React-Bootstrap 1.0.1  everything worked fine but in React-Bootstrap 1.3.0 the code will not compile unless, as you mentioned, you use esModuleInterop or allowSyntheticDefaultImports.   This can become a big issue for many of your users who may have their existing code impacted by adding this settings.   For instance in my case I was able to solve the issue by adding allowSyntheticDefaultImports=true in my tsconfig.  But if I use esModuleInterop then I get a lot of compilation errors in other files of my project.  Using import * as React will allow your users to CHOOSE whether they want to use allowSyntheticDefaultImports or not esModuleInterop. I think it is better give your users the freedom to chose rather than force them. I consider this important for backward compatibility for 1.0.1 existing projects

**Comment by calvinMcM** [comment]
Adding the two typescript configuration adaptations does seem to resolve the issue.

I can't speak for everyone, but In general, the `* as React` style is more useful to me. Thankfully the added settings don't seem to impact my product negatively. If the package will only work with the above settings in place, it might be helpful to note that detail in the [documentation pages](https://react-bootstrap.github.io/), perhaps in a section for TS support and best practices.

I've been using this package for several years, and so far have had few difficulties with it, so props to your dev team.

**Comment by taion** [comment]
Is there a way we can make Babel or TypeScript compile that appropriately? cc @jquense It does feel a bit odd to impose this on all of our users.

**Comment by jquense** [comment]
> It does feel a bit odd to impose this on all of our users.

This has been the case for all of our packages inadvertently. I don't actually think it's that big of a deal, since (judging from the volume of issues) most TS users use the interop. And that makes sense, the compiler setting was adding partly to solve these issues and address TS's own bad assumptions about CJS to ESM. The "most" correct thing for us to do would be to use `import React = require('react')` syntax but bleh. 

Ultimately this will be fixed upstream with the new JSX transform for auto including the right import and React actually switching to esm. For now tho, changing this would be an uphill battle against intellisense, and other tooling, and also results in switch entirely to namesapce usage of React exports or importing it twice (items by name and by `* as`) in order to appease jsx

**Comment by ashish2rathi** [comment]
Did anyone got solution for this. I am also facing the same issue after upgrading the bootstrap version.
I am already importing like `import * as React from 'react'`;

**Comment by felipecarrillo100** [comment]
@ashish2rathi is not you who has to use 
import * as React from 'react'; 

The issue is that the Tab.js  is using the syntax 

import React from 'react'; 

Which is not supported by your Typescript configuration.  
I requested them to change the import in Tab.js but so far this ha been refused,  So, if you want this to run in your project then you need to change your Typescript settings to support:

import React from 'react'; 

Google esModuleInterop or allowSyntheticDefaultImports.  Or just google how to import import React from 'react'

**Comment by kyletsang** [comment]
Fixed in v2 alpha
