### ISSUE TITLE
ownerWindow.js throws "babelHelpers.interopRequireDefault is not a function" in browserify bundle

### ISSUE THREAD

**Issue by mdarens** [react-bootstrap/react-bootstrap#1372]
After upgrading from 0.24.4 to 0.25.2, I get this error when importing react-bootstrap components ([similar issue with react-widgets](/jquense/react-widgets/issues/205)). I'm using grunt-browserify 4.0.0 and uglifyify 3.0.1.

**Comment by taion** [comment]
Per discussion there that looks like Browserify is somehow messing up your imports, no? These are working fine for me. There isn't even an `ownerWindow.js` in this repo.

**Comment by mdarens** [comment]
D'oh. Thanks. Time to have fun with my build.

**Comment by paulgoertzen** [comment]
I'm having this same problem. Mdarens, did you come up with a solution?

**Comment by mdarens** [comment]
In my case we had a browserify build using `derequire` which was replacing `require` and `define` calls. The (gross) solution was to include `babel-polyfill` before everything and use `browserify-replace` with `global: true` (since it's a transform and `derequire` is a plugin) to cross over the module boundary and replace all remaining `define` calls left in the distributed code of our deps. A more robust solution would probably use `graspify` to do this bit.
