### ISSUE TITLE
Regression: Use of OverlayTrigger results in Javascript exception: Uncaught TypeError: "e._reactInternalInstance._processChildContext is not a function"

### ISSUE THREAD

**Issue by agmathew** [react-bootstrap/react-bootstrap#1235]
I just tried upgrading from version 0.24.4 to 0.25.100 and I'm getting this exception when using an OverlayTrigger:

    Uncaught TypeError: "e._reactInternalInstance._processChildContext is not a function"

Here's a JSFiddle demonstrating the issue:

http://jsfiddle.net/hy21c986/

This code previously worked in 0.24.4. I'm testing in Chrome 44.0.2403.157.

**Comment by taion** [comment]
The only release on v0.25.100 is the -react-pre.0, which is a pre-release for React v0.14 compatibility, and has peer dependencies set up as such. You should not be using that release if you're not using React v0.14, which it sounds like you were not because there was no v0.24.4 release with React v0.14 compatibility.

Please install the stable release of v0.25.0 instead.
